### PR TITLE
Test Apache ORC 1.8.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by wgtmac**

### CODE REVIEW

**Comment by wgtmac** [comment]
https://github.com/wgtmac/spark/actions/runs/6044325795/job/16405800755?pr=4

It seems that **Spark on Kubernetes Integration test** cannot pass. Is it a blocker?

@dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
No, `VolcanoSuite` is one of batch scheduler of K8s module. It's irrelevant and also a known flaky one. Please re-trigger the `Failed Pipeline`.
```
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	org.apache.spark.deploy.k8s.integrationtest.VolcanoSuite
```

**Comment by dongjoon-hyun** [comment]
Ping, @wgtmac for the above.

**Comment by wgtmac** [comment]
Thank you for the info! @dongjoon-hyun 

Actually I’ve retried several times and it keeps failing. So I will go ahead the release process.

**Pull request closed without merging**
