### PR TITLE
Test Apache ORC 1.9.3-SNAPSHOT

### PR DESCRIPTION
**Pull request by wgtmac**

### CODE REVIEW

**Comment by wgtmac** [comment]
The failure of python linter in https://github.com/wgtmac/spark/actions/runs/8312721080/job/22748412563?pr=6 should be unrelated.

```
starting mypy annotations test...
annotations failed mypy checks:
/usr/local/lib/python3.9/dist-packages/torch/_dynamo/mutation_guard.py:1: error: disable_error_code: Invalid error code(s): method-assign  [misc]
/usr/local/lib/python3.9/dist-packages/torch/_dynamo/eval_frame.py:1: error: disable_error_code: Invalid error code(s): method-assign  [misc]
/usr/local/lib/python3.9/dist-packages/torch/_dynamo/debug_utils.py:1: error: disable_error_code: Invalid error code(s): method-assign  [misc]
python/pyspark/pandas/plot/matplotlib.py:23: error: Module "matplotlib.axes._base" has no attribute "_process_plot_format"  [attr-defined]
Found 4 errors in 4 files (checked 688 source files)
1
Error: Process completed with exit code 1.
```

**Comment by wgtmac** [comment]
Same with RC0. I will ignore those unrelated failures: https://github.com/wgtmac/spark/pull/7

**Comment by dongjoon-hyun** [comment]
Could you rebase once more, please?
PySpark tests should pass now (except the Python linter failure)

**Comment by wgtmac** [comment]
Done!

**Pull request closed without merging**
