### PR TITLE
Test Apache ORC 1.9.3 RC0

### PR DESCRIPTION
**Pull request by wgtmac**

### CODE REVIEW

**Comment by wgtmac** [comment]
It seems that all failures are about python and unrelated.

**Comment by dongjoon-hyun** [comment]
Yes, I found that recently two days ago and had been investigating this here.
- #45545

Apache Spark CI will be recovered during this weekend, @wgtmac .

**Comment by wgtmac** [comment]
@dongjoon-hyun Thanks! Then I will ignore these unrelated failures.

**Comment by dongjoon-hyun** [comment]
Could you rebase once more, please?
PySpark tests should pass now (except the Python linter failure)

**Comment by wgtmac** [comment]
Done!

**Comment by dongjoon-hyun** [comment]
Thank you.

Could you re-trigger the failed-pipeline only?
- https://github.com/wgtmac/spark/actions/runs/8335890609/job/22812181330?pr=7

**Pull request closed without merging**
